// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://barvljqnoeutfcgpzvzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcnZsanFub2V1dGZjZ3B6dnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTc0MDQsImV4cCI6MjA3MzY5MzQwNH0.95NIT_iYPZ9VxwLRBGCZTdB1uwByvka86yaCe42pJfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});